name: minimal
description: A minimalistic Flutter website template for blogs and portfolios.
version: 2.1.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
#  responsive_framework:
#    path: ../
  # Uncomment to build standalone project.
  responsive_framework: ^1.5.1
  google_fonts: ^6.2.1
  animations: ^2.0.11
  loading_gifs: ^0.3.0
  url_launcher: ^6.3.0 # Requires setup.
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  flutter_web_optimizer: ^1.5.1
  provider: ^6.0.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  # Для редактора кода с подсветкой синтаксиса
  code_text_field: ^1.1.0

  flutter_markdown: ^0.7.1 # Для отображения Markdown
  
  # Для отображения HTML/CSS превью
  flutter_widget_from_html_core: ^0.15.2
  
  # Для запуска JS-кода в веб-вью
  universal_html: ^2.2.4
  webview_flutter: ^4.7.0 # для мобильных платформ в будущем
  webview_flutter_web: ^0.2.2+4 # для веб
  split_view: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/Minimal-Logo.png"
  image_path_android: "assets/Minimal-Logo.png"
  image_path_ios: "assets/Minimal-Logo-iOS.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/Minimal-Logo-Adaptive.png"
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/portfolio/
    - assets/images/marocco/
    - assets/images/georgia_1/
    - assets/images/seo-ai-era/
    - assets/images/seo-guides/
    - assets/images/dev-guides/
    - assets/images/service-logos/
    - assets/marocco_photos_pack.zip
    - assets/georgia_1_photos_pack.zip